artifact_location: file:///C:/Users/Catalina/OneDrive/Documentos/DocumentosSistema/Maestria/analitica
  de datos/proyecto/content/316913808144788301
creation_time: 1715030435623
experiment_id: '316913808144788301'
last_update_time: 1715030435623
lifecycle_stage: active
name: Modelos
